### ISSUE TITLE
Running TMI behind proxy

### ISSUE THREAD

**Issue by blandfried** [addyosmani/tmi#21]
I noticed I get a connection timeout and I believe it is because I am working behind a corporate proxy. 

>tmi www.google.com --verbose
connect ETIMEDOUT

I can use npm behind the proxy because it has options to set up the proxy connection.

**Comment by sindresorhus** [comment]
You need to set up the correct environment variables for the proxy: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables
